"""empty message

Revision ID: 3fe5c2d51bef
Revises: 701494562f8d
Create Date: 2021-10-17 17:15:48.878614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe5c2d51bef'
down_revision = '701494562f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('title', sa.String(), nullable=False))
    op.add_column('carts', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('carts', sa.Column('image', sa.String(), nullable=False))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('product_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'carts', 'products', ['product_id'], ['id'])
    op.drop_column('carts', 'image')
    op.drop_column('carts', 'price')
    op.drop_column('carts', 'title')
    # ### end Alembic commands ###
